### ISSUE TITLE
SH-01A - intervals not shown for ASGNCHORD 2-4

### ISSUE THREAD

**Issue by AlesBlaha** [TheCase/synthesizer_patch_visualizer#1]
[rendered image](https://spv.repulsor.net/sh01a/image.php?s=33&data=jLdIf6qMT%2BQoLhmXpQnFX8eOXGeTQrjKRXYkBVczZLKtKsd2Id9reO2Q2HvmTNObhJSwAex5rRQoDEc4WXlrg8uCEDrxAPGpYpAoU90CIG0kKGahIYsVcGddVuz4UChYK3UeGuvE5%2FrT%2BxNakUBYrg%2BzF9oyc4PHFGiH9zB0CsM%3D)

Patch:
`LfoRate	= 0
LfoMode	= 0
LfoWaveform	= 2
VcoModDepth	= 0
VcoRange	= 5
VcoPulseWidth	= 92
VcoPwmSource	= 1
MixPwmLevel	= 255
MixSawLevel	= 0
MixSubLevel	= 0
MixSubType	= 2
MixNoiseLevel	= 0
VcfCutoff	= 143
VcfResonance	= 255
VcfEnvDepth	= 0
VcfModDepth	= 0
VcfKeyFollow	= 255
VcaEnvMode	= 1
EnvTrgMode	= 2
EnvAttack	= 0
EnvDecay	= 78
EnvSustain	= 0
EnvRelease	= 41
AsgnMode	= 3
BendDepthVco	= 0
BendDepthVcf	= 255
ModDepth	= 255
PortamentoMode	= 0
PortamentoTime	= 0
NoiseMode	= 0
AsgnChord 2	= SW=1,SHIFT=3
AsgnChord 3	= SW=1,SHIFT=-6
AsgnChord 4	= SW=1,SHIFT=9`

**Comment by TheCase** [comment]
Ah!  Thanks for the bug report.  Got it all patched up for you.  Thanks for reporting it :)
